-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.departments
(

    CONSTRAINT departments_pkey PRIMARY KEY (dept_no)
);

CREATE TABLE IF NOT EXISTS public.titles
(

    CONSTRAINT titles_pkey PRIMARY KEY (title_id)
);

CREATE TABLE IF NOT EXISTS public.dept_emp
(
)
;

CREATE TABLE IF NOT EXISTS public.dept_managemer
(
)
;

CREATE TABLE IF NOT EXISTS public.employees
(

    CONSTRAINT employees_pkey PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS public.salaries
(

    CONSTRAINT salaries_pkey PRIMARY KEY (salary)
);

ALTER TABLE IF EXISTS public.dept_emp
    ADD CONSTRAINT emp_no FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH FULL
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_emp
    ADD CONSTRAINT dept_no FOREIGN KEY (dept_no)
    REFERENCES public.departments (dept_no) MATCH FULL
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_managemer
    ADD CONSTRAINT emp_no FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_managemer
    ADD CONSTRAINT dept_no FOREIGN KEY (dept_no)
    REFERENCES public.departments (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT title_id FOREIGN KEY (emp_title_id)
    REFERENCES public.titles (title_id) MATCH FULL
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salaries
    ADD CONSTRAINT emp_no FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;